### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by aidanporter** [steisn/blazebot#3]
Keep getting this error

Personal and payment data form sent :D
Nov 06 00:26:05.0611: [INFO]    Analysing server response ...
Nov 06 00:26:05.0612: [INFO]    
Nov 06 00:26:05.0613: [INFO]    Status: [ FAILURE ]

**Comment by steisn** [comment]
Status [FAILURE] means that the shop has rejected your order.
Please review your personal and payment settings.
For example a random credit card number also generates
this message.

PS. During this stage, SSL connection is already done.
